[run]
timeout = "5m"
concurrency = 4
tests = false

[linters-settings.exhaustive]
default-signifies-exhaustive = true

[linters-settings.revive]
ignore-generated-header = false
severity = "warning"
confidence = 0.8

[linters-settings.goimports]
local-prefixes = "github.com/Karzoug/goph_keeper"

[linters]
disable-all = true
enable = [
  "bodyclose",
  "dogsled",
  "dupl",
  "errcheck",
  "goimports",
  "goprintffuncname",
  "gosec",
  "gosimple",
  "govet",
  "ineffassign",
  "misspell",
  "exportloopref",
  "staticcheck",
  "stylecheck",
  "typecheck",
  "unconvert",
  "unused",
  "whitespace",
  "gocyclo",
  "exhaustive",
  "typecheck",
  "asciicheck",
  "errorlint",
  "revive",
]