// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.12.4
// source: common/api/fserver.proto

package fstorage

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetFileDownloadURLRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Key   string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *GetFileDownloadURLRequest) Reset() {
	*x = GetFileDownloadURLRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_api_fserver_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFileDownloadURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileDownloadURLRequest) ProtoMessage() {}

func (x *GetFileDownloadURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_api_fserver_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileDownloadURLRequest.ProtoReflect.Descriptor instead.
func (*GetFileDownloadURLRequest) Descriptor() ([]byte, []int) {
	return file_common_api_fserver_proto_rawDescGZIP(), []int{0}
}

func (x *GetFileDownloadURLRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GetFileDownloadURLRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetFileDownloadURLResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *GetFileDownloadURLResponse) Reset() {
	*x = GetFileDownloadURLResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_api_fserver_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFileDownloadURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileDownloadURLResponse) ProtoMessage() {}

func (x *GetFileDownloadURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_api_fserver_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileDownloadURLResponse.ProtoReflect.Descriptor instead.
func (*GetFileDownloadURLResponse) Descriptor() ([]byte, []int) {
	return file_common_api_fserver_proto_rawDescGZIP(), []int{1}
}

func (x *GetFileDownloadURLResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type GetFileUploadURLRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Key   string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Size  int64  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *GetFileUploadURLRequest) Reset() {
	*x = GetFileUploadURLRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_api_fserver_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFileUploadURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileUploadURLRequest) ProtoMessage() {}

func (x *GetFileUploadURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_api_fserver_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileUploadURLRequest.ProtoReflect.Descriptor instead.
func (*GetFileUploadURLRequest) Descriptor() ([]byte, []int) {
	return file_common_api_fserver_proto_rawDescGZIP(), []int{2}
}

func (x *GetFileUploadURLRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GetFileUploadURLRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GetFileUploadURLRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type GetFileUploadURLResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UploadId string   `protobuf:"bytes,1,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	Urls     []string `protobuf:"bytes,2,rep,name=urls,proto3" json:"urls,omitempty"`
}

func (x *GetFileUploadURLResponse) Reset() {
	*x = GetFileUploadURLResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_api_fserver_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFileUploadURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileUploadURLResponse) ProtoMessage() {}

func (x *GetFileUploadURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_api_fserver_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileUploadURLResponse.ProtoReflect.Descriptor instead.
func (*GetFileUploadURLResponse) Descriptor() ([]byte, []int) {
	return file_common_api_fserver_proto_rawDescGZIP(), []int{3}
}

func (x *GetFileUploadURLResponse) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *GetFileUploadURLResponse) GetUrls() []string {
	if x != nil {
		return x.Urls
	}
	return nil
}

type CompleteFileUploadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email    string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Key      string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	UploadId string   `protobuf:"bytes,3,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	Etags    []string `protobuf:"bytes,4,rep,name=etags,proto3" json:"etags,omitempty"`
}

func (x *CompleteFileUploadRequest) Reset() {
	*x = CompleteFileUploadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_api_fserver_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompleteFileUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteFileUploadRequest) ProtoMessage() {}

func (x *CompleteFileUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_api_fserver_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteFileUploadRequest.ProtoReflect.Descriptor instead.
func (*CompleteFileUploadRequest) Descriptor() ([]byte, []int) {
	return file_common_api_fserver_proto_rawDescGZIP(), []int{4}
}

func (x *CompleteFileUploadRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CompleteFileUploadRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CompleteFileUploadRequest) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *CompleteFileUploadRequest) GetEtags() []string {
	if x != nil {
		return x.Etags
	}
	return nil
}

type CompleteFileUploadResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CompleteFileUploadResponse) Reset() {
	*x = CompleteFileUploadResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_api_fserver_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompleteFileUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteFileUploadResponse) ProtoMessage() {}

func (x *CompleteFileUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_api_fserver_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteFileUploadResponse.ProtoReflect.Descriptor instead.
func (*CompleteFileUploadResponse) Descriptor() ([]byte, []int) {
	return file_common_api_fserver_proto_rawDescGZIP(), []int{5}
}

type AbortFileUploadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email    string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Key      string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	UploadId string `protobuf:"bytes,3,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
}

func (x *AbortFileUploadRequest) Reset() {
	*x = AbortFileUploadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_api_fserver_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AbortFileUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortFileUploadRequest) ProtoMessage() {}

func (x *AbortFileUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_api_fserver_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortFileUploadRequest.ProtoReflect.Descriptor instead.
func (*AbortFileUploadRequest) Descriptor() ([]byte, []int) {
	return file_common_api_fserver_proto_rawDescGZIP(), []int{6}
}

func (x *AbortFileUploadRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AbortFileUploadRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *AbortFileUploadRequest) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

type AbortFileUploadResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AbortFileUploadResponse) Reset() {
	*x = AbortFileUploadResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_api_fserver_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AbortFileUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortFileUploadResponse) ProtoMessage() {}

func (x *AbortFileUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_api_fserver_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortFileUploadResponse.ProtoReflect.Descriptor instead.
func (*AbortFileUploadResponse) Descriptor() ([]byte, []int) {
	return file_common_api_fserver_proto_rawDescGZIP(), []int{7}
}

var File_common_api_fserver_proto protoreflect.FileDescriptor

var file_common_api_fserver_proto_rawDesc = []byte{
	0x0a, 0x18, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x66, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x66, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65,
	0x22, 0x43, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x44, 0x6f, 0x77, 0x6e, 0x6c,
	0x6f, 0x61, 0x64, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d,
	0x61, 0x69, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x2e, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x65,
	0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x75, 0x72, 0x6c, 0x22, 0x55, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x65,
	0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x22, 0x4b, 0x0a, 0x18,
	0x47, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x55, 0x52, 0x4c,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x70, 0x6c, 0x6f,
	0x61, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x70, 0x6c,
	0x6f, 0x61, 0x64, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x72, 0x6c, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x04, 0x75, 0x72, 0x6c, 0x73, 0x22, 0x76, 0x0a, 0x19, 0x43, 0x6f, 0x6d,
	0x70, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x1b,
	0x0a, 0x09, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x65,
	0x74, 0x61, 0x67, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x65, 0x74, 0x61, 0x67,
	0x73, 0x22, 0x1c, 0x0a, 0x1a, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x69, 0x6c,
	0x65, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x5d, 0x0a, 0x16, 0x41, 0x62, 0x6f, 0x72, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x55, 0x70, 0x6c, 0x6f,
	0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61,
	0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x64, 0x22, 0x19,
	0x0a, 0x17, 0x41, 0x62, 0x6f, 0x72, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x55, 0x70, 0x6c, 0x6f, 0x61,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xe9, 0x03, 0x0a, 0x12, 0x47, 0x6f,
	0x70, 0x68, 0x4b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x46, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65,
	0x12, 0x77, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x44, 0x6f, 0x77, 0x6e, 0x6c,
	0x6f, 0x61, 0x64, 0x55, 0x52, 0x4c, 0x12, 0x2f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x66, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x47, 0x65,
	0x74, 0x46, 0x69, 0x6c, 0x65, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x55, 0x52, 0x4c,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x30, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x66, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x47,
	0x65, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x55, 0x52,
	0x4c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x71, 0x0a, 0x10, 0x47, 0x65, 0x74,
	0x46, 0x69, 0x6c, 0x65, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x55, 0x52, 0x4c, 0x12, 0x2d, 0x2e,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x66, 0x73, 0x74, 0x6f,
	0x72, 0x61, 0x67, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x55, 0x70, 0x6c, 0x6f,
	0x61, 0x64, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2e, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x66, 0x73, 0x74, 0x6f, 0x72,
	0x61, 0x67, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x55, 0x70, 0x6c, 0x6f, 0x61,
	0x64, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x77, 0x0a, 0x12,
	0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x55, 0x70, 0x6c, 0x6f,
	0x61, 0x64, 0x12, 0x2f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x67, 0x72, 0x70, 0x63,
	0x2e, 0x66, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65,
	0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x30, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x66, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x6c,
	0x65, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x6e, 0x0a, 0x0f, 0x41, 0x62, 0x6f, 0x72, 0x74, 0x46, 0x69,
	0x6c, 0x65, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x2c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x66, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e,
	0x41, 0x62, 0x6f, 0x72, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2d, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x66, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x41, 0x62,
	0x6f, 0x72, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x16, 0x5a, 0x14, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f,
	0x67, 0x72, 0x70, 0x63, 0x2f, 0x66, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_common_api_fserver_proto_rawDescOnce sync.Once
	file_common_api_fserver_proto_rawDescData = file_common_api_fserver_proto_rawDesc
)

func file_common_api_fserver_proto_rawDescGZIP() []byte {
	file_common_api_fserver_proto_rawDescOnce.Do(func() {
		file_common_api_fserver_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_api_fserver_proto_rawDescData)
	})
	return file_common_api_fserver_proto_rawDescData
}

var file_common_api_fserver_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_common_api_fserver_proto_goTypes = []interface{}{
	(*GetFileDownloadURLRequest)(nil),  // 0: common.grpc.fstorage.GetFileDownloadURLRequest
	(*GetFileDownloadURLResponse)(nil), // 1: common.grpc.fstorage.GetFileDownloadURLResponse
	(*GetFileUploadURLRequest)(nil),    // 2: common.grpc.fstorage.GetFileUploadURLRequest
	(*GetFileUploadURLResponse)(nil),   // 3: common.grpc.fstorage.GetFileUploadURLResponse
	(*CompleteFileUploadRequest)(nil),  // 4: common.grpc.fstorage.CompleteFileUploadRequest
	(*CompleteFileUploadResponse)(nil), // 5: common.grpc.fstorage.CompleteFileUploadResponse
	(*AbortFileUploadRequest)(nil),     // 6: common.grpc.fstorage.AbortFileUploadRequest
	(*AbortFileUploadResponse)(nil),    // 7: common.grpc.fstorage.AbortFileUploadResponse
}
var file_common_api_fserver_proto_depIdxs = []int32{
	0, // 0: common.grpc.fstorage.GophKeeperFStorage.GetFileDownloadURL:input_type -> common.grpc.fstorage.GetFileDownloadURLRequest
	2, // 1: common.grpc.fstorage.GophKeeperFStorage.GetFileUploadURL:input_type -> common.grpc.fstorage.GetFileUploadURLRequest
	4, // 2: common.grpc.fstorage.GophKeeperFStorage.CompleteFileUpload:input_type -> common.grpc.fstorage.CompleteFileUploadRequest
	6, // 3: common.grpc.fstorage.GophKeeperFStorage.AbortFileUpload:input_type -> common.grpc.fstorage.AbortFileUploadRequest
	1, // 4: common.grpc.fstorage.GophKeeperFStorage.GetFileDownloadURL:output_type -> common.grpc.fstorage.GetFileDownloadURLResponse
	3, // 5: common.grpc.fstorage.GophKeeperFStorage.GetFileUploadURL:output_type -> common.grpc.fstorage.GetFileUploadURLResponse
	5, // 6: common.grpc.fstorage.GophKeeperFStorage.CompleteFileUpload:output_type -> common.grpc.fstorage.CompleteFileUploadResponse
	7, // 7: common.grpc.fstorage.GophKeeperFStorage.AbortFileUpload:output_type -> common.grpc.fstorage.AbortFileUploadResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_api_fserver_proto_init() }
func file_common_api_fserver_proto_init() {
	if File_common_api_fserver_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_common_api_fserver_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFileDownloadURLRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_api_fserver_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFileDownloadURLResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_api_fserver_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFileUploadURLRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_api_fserver_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFileUploadURLResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_api_fserver_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompleteFileUploadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_api_fserver_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompleteFileUploadResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_api_fserver_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AbortFileUploadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_api_fserver_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AbortFileUploadResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_api_fserver_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_common_api_fserver_proto_goTypes,
		DependencyIndexes: file_common_api_fserver_proto_depIdxs,
		MessageInfos:      file_common_api_fserver_proto_msgTypes,
	}.Build()
	File_common_api_fserver_proto = out.File
	file_common_api_fserver_proto_rawDesc = nil
	file_common_api_fserver_proto_goTypes = nil
	file_common_api_fserver_proto_depIdxs = nil
}
