name: lint
on:
    pull_request:
    push:
      branches:
        - main

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: false
      - name: golangci-lint (server)
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54.1
          working-directory: server
      - name: golangci-lint (client)
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54.1
          working-directory: client
      - name: golangci-lint (pkg)
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54.1
          working-directory: pkg