name: release

on:
    release:
      types: [created]

permissions:
  contents: write
  packages: write

jobs:
    releases-matrix:
      name: Release Go Binary
      runs-on: ubuntu-latest
      strategy:
        matrix:
          goos: [linux, windows, darwin]
          goarch: ["386", amd64, arm64]
          exclude:
            - goarch: "386"
              goos: darwin
            - goarch: "386"
              goos: windows
      steps:
      - uses: actions/checkout@v3
      - name: Set APP_VERSION env
        run: echo APP_VERSION=$(echo ${GITHUB_REF} | rev | cut -d'/' -f 1 | rev ) >> ${GITHUB_ENV}
      - name: Set BUILD_TIME env
        run: echo BUILD_TIME=$(date) >> ${GITHUB_ENV}
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          project_path: "./client/cmd/"
          binary_name: "client"
          ldflags: -X "main.buildVersion=${{ env.APP_VERSION }}" -X "main.buildDate=${{ env.BUILD_TIME }}"