name: tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  unit:
    runs-on: ubuntu-latest
    container: golang:1.20
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Test
        run: cd server && go test -tags fast -coverprofile unit.txt -covermode atomic ./...
      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./server/unit.txt
          flags: unit
          token: ${{ secrets.CODECOV_TOKEN }}
          name: unit